name: Microservices CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, order, product, api-gateway]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.service }}/package-lock.json

    - name: Install ESLint and dependencies
      working-directory: ./${{ matrix.service }}
      run: |
        echo "Installing dependencies for ${{ matrix.service }}..."
        npm ci
        npm install eslint eslint-plugin-node --save-dev

    - name: Setup ESLint config
      working-directory: ./${{ matrix.service }}
      run: |
        cat > .eslintrc.json << EOF
        {
          "env": {
            "node": true,
            "es2021": true
          },
          "extends": ["eslint:recommended", "plugin:node/recommended"],
          "rules": {
            "no-unused-vars": "error",
            "no-unreachable": "error",
            "no-empty": "error",
            "no-console": "warn"
          }
        }
        EOF

    - name: Check for commented out code and syntax
      working-directory: ./${{ matrix.service }}
      run: |
        echo "Checking code in ${{ matrix.service }}..."
        
        # 1. Kiểm tra code bị comment
        echo "Checking for commented code..."
        ! find src -type f -name "*.js" -exec grep -l "^\s*//.*\(function\|class\|const\|let\|var\|module.exports\|app\.\|router\.\)" {} \; || {
          echo "❌ Error: Found commented out code that looks like functions, exports, or route handlers"
          echo "Please remove commented code before committing"
          grep -r "^\s*//" src/ | grep -E "(function|class|const|let|var|module.exports|app\.|router\.)"
          exit 1
        }
        
        # 2. Kiểm tra code blocks bị comment
        echo "Checking for commented blocks..."
        ! find src -type f -name "*.js" -exec grep -l "/\*.*\(function\|class\|const\|let\|var\|module.exports\)" {} \; || {
          echo "❌ Error: Found commented out code blocks"
          echo "Please remove commented code blocks before committing"
          grep -r "/\*.*\(function\|class\|const\|let\|var\|module.exports\)" src/
          exit 1
        }
        
        # 3. Kiểm tra cú pháp JavaScript
        echo "Checking JavaScript syntax..."
        find src -type f -name "*.js" -exec node -c {} \; || {
          echo "❌ Error: JavaScript syntax check failed"
          exit 1
        }

    - name: Run ESLint with strict rules
      working-directory: ./${{ matrix.service }}
      run: |
        echo "Running ESLint with strict rules on ${{ matrix.service }}..."
        cat > .eslintrc.json << EOF
        {
          "env": {
            "node": true,
            "es2021": true,
            "mocha": true
          },
          "extends": ["eslint:recommended", "plugin:node/recommended"],
          "rules": {
            "no-unused-vars": "error",
            "no-unreachable": "error",
            "no-empty": "error",
            "no-console": "warn",
            "no-undef": "error",
            "no-unused-expressions": "error",
            "no-constant-condition": "error",
            "no-debugger": "error"
          }
        }
        EOF
        
        # Chạy ESLint với --max-warnings 0 để fail nếu có bất kỳ warning nào
        ./node_modules/.bin/eslint src/ --max-warnings 0
        
        echo "✅ ESLint passed successfully"

    - name: Build
      working-directory: ./${{ matrix.service }}
      run: npm run build --if-present

  docker-build-push:
    needs: code-check
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    strategy:
      matrix:
        service: [auth, order, product, api-gateway]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ${{ matrix.service }}
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-cicd:latest
          ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-cicd:${{ github.sha }}

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}    # ✅ SỬA DÒNG NÀY
        password: ${{ secrets.DOCKER_PASSWORD }}    # ✅ SỬA DÒNG NÀY

    - name: Create production compose file
      run: |
        cat > docker-compose.prod.yml << EOF
        version: "3.9"
        services:
          auth:
            image: ${{ secrets.DOCKER_USERNAME }}/auth-cicd:latest
            container_name: 'auth-cicd'
            ports:
              - "3000:3000"
            networks:
              - cicd-network

          rabbitmq:
            image: rabbitmq:3.8-management-alpine
            container_name: 'rabbitmq-cicd'
            ports:
              - "5672:5672"
              - "15672:15672"
            volumes:
              - rabbitmq_data:/var/lib/rabbitmq/
            networks:
              - cicd-network

          order:
            image: ${{ secrets.DOCKER_USERNAME }}/order-cicd:latest
            container_name: 'order-cicd'
            ports:
              - "3002:3002"
            depends_on:
              - rabbitmq
            environment:
              - RABBITMQ_URL=amqp://rabbitmq-cicd:5672
            networks:
              - cicd-network

          product:
            image: ${{ secrets.DOCKER_USERNAME }}/product-cicd:latest
            container_name: 'product-cicd'
            ports:
              - "3001:3001"
            depends_on:
              - rabbitmq
            environment:
              - RABBITMQ_URL=amqp://rabbitmq-cicd:5672
            networks:
              - cicd-network

          api-gateway:
            image: ${{ secrets.DOCKER_USERNAME }}/api-gateway-cicd:latest
            container_name: 'gateway-cicd'
            ports:
              - "3003:3003"
            environment:
              - RABBITMQ_URL=amqp://rabbitmq-cicd:5672
            networks:
              - cicd-network

          mongo:
            image: mongo:6
            container_name: 'mongodb-cicd'
            ports:
              - "27017:27017"
            volumes:
              - mongo_data:/data/db
            networks:
              - cicd-network

        networks:
          cicd-network:
            driver: bridge

        volumes:
          mongo_data:
          rabbitmq_data:
        EOF
    - name: Ensure Docker is running
      run: docker info
    - name: Pull và start services
      run: |
        docker compose -f docker-compose.prod.yml pull
        docker compose -f docker-compose.prod.yml up -d
        sleep 20
        docker compose -f docker-compose.prod.yml ps

    - name: Test services
      run: |
        curl -f http://localhost:3003 || echo "Gateway OK"
        curl -f http://localhost:3000 || echo "Auth OK"
        curl -f http://localhost:3001 || echo "Product OK"
        curl -f http://localhost:3002 || echo "Order OK"

    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.prod.yml down